version: 2.1

orbs:
  platform-orb: okta/general-platform-helpers@1.6

aliases:

  - &build_steps
    - checkout
    - platform-orb/step-load-dependencies
    - run: java -version
    - run: ./mvnw clean install -Dlicense.skip=true -Pci
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*IT.txt
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*dump*

jobs:
  jdk8:
    docker:
      - image: cimg/openjdk:8.0.362-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

  jdk11:
    docker:
      - image: cimg/openjdk:11.0.18-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

  jdk17:
    docker:
      - image: cimg/openjdk:17.0.6-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

workflows:
  "Circle CI Tests":
    jobs:
      - platform-orb/job-secrets-obtain:
          name: cache-secrets
          secret-key: "OKTA_CLIENT_ORGURL;OKTA_CLIENT_TOKEN;OKTA_AUTHN_ITS_MFAENROLLGROUPID"
      - jdk8:
          requires:
            - cache-secrets
      - jdk11:
          requires:
            - cache-secrets
      - jdk17:
          requires:
            - cache-secrets
