version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@5.1

aliases:

  - &build_steps
    - checkout
    - general-platform-helpers/step-load-dependencies
    - run: java -version
    - run: ./mvnw clean install -Dlicense.skip=true -Pci
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*IT.txt
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*dump*

jobs:

  jdk17:
    docker:
      - image: cimg/openjdk:17.0.11-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

  jdk21:
    docker:
      - image: cimg/openjdk:21.0.2-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

  snyk-scan:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: ./mvnw clean install -Pci -Dlicense.skip=true -Dmaven.test.skip.exec=true
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: false
          skip-unresolved: false
          run-on-non-main: true
          additional-arguments: "--maven-aggregate-project"

  reversing-labs:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Download Reverse Labs Scanner
          command: |
            curl https://dso-resources.oktasecurity.com/scanner \
              -H "x-api-key: $RESOURCE_TOKEN" \
              --output rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      # Install the wrapper that was downloaded
      - run:
          name: Install RL Wrapper
          command: |
            pip install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      # Setup the AWS profile
      - aws-cli/setup:
          profile_name: default
          role_arn: $AWS_ARN
          region: us-east-1
      # Get the credentials and save to env
      - run: >-
          eval "$(aws configure export-credentials --profile default --format env)" 2> /dev/null
      # Run the wrapper, do not change anything here
      - run:
          name: Run Reversing Labs Wrapper Scanner
          command: |
            rl-wrapper \
              --artifact ${CIRCLE_WORKING_DIRECTORY/#\~/$HOME} \
              --name $CIRCLE_PROJECT_REPONAME\
              --version $CIRCLE_SHA1\
              --repository $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --commit $CIRCLE_SHA1 \
              --build-env "circleci" \
              --suppress_output    
workflows:
  "Circle CI Tests":
    jobs:
      - jdk17
      - jdk21
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          context:
            - static-analysis
      - snyk-scan:
          name: execute-snyk
          requires:
            - jdk21
          context:
            - static-analysis
  "Malware Scanner":
    jobs:
      - reversing-labs:
          context:
            - okta-dcp  
