version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

aliases:

  - &build_steps
    - checkout
    - general-platform-helpers/step-load-dependencies
    - run: java -version
    - run: ./mvnw clean install -Dlicense.skip=true -Pci
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*IT.txt
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*dump*

jobs:
  jdk8:
    docker:
      - image: cimg/openjdk:8.0.362-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

  jdk11:
    docker:
      - image: cimg/openjdk:11.0.18-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

  jdk17:
    docker:
      - image: cimg/openjdk:17.0.6-node
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

  snyk-scan:
    docker:
      - image: cimg/openjdk:17.0.6-node
    steps:
      - checkout
      - run: ./mvnw clean install -DskipITs
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: false
          skip-unresolved: false
          run-on-non-main: true
          additional-arguments: "--maven-aggregate-project"

workflows:
  "Circle CI Tests":
    jobs:
      - general-platform-helpers/job-secrets-obtain:
          name: cache-secrets
          secret-key: "OKTA_CLIENT_ORGURL;OKTA_CLIENT_TOKEN;OKTA_AUTHN_ITS_MFAENROLLGROUPID"
      - jdk8:
          requires:
            - cache-secrets
      - jdk11:
          requires:
            - cache-secrets
      - jdk17:
          requires:
            - cache-secrets
  # See OKTA-624750
  semgrep:
    jobs:
      - jdk17
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare
      - general-platform-helpers/job-snyk-prepare:
          name: prepare-snyk
          requires:
            - jdk17
      - snyk-scan:
          name: execute-snyk
          requires:
            - prepare-snyk
