version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9.4
  platform-helpers: okta/platform-helpers@1
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@5.1

jobs:
  build-and-test:
    parameters:
      jdk_version:
        type: string
        default: "17.0.11"
      node_image:
        type: string
        default: "cimg/openjdk:17.0.11-node"
    docker:
      - image: << parameters.node_image >>
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps:
      - checkout
      - general-platform-helpers/step-load-dependencies
      - run: java -version
      - run: ./mvnw clean install -Dlicense.skip=true -Pci
      - run:
          when: on_fail
          command: cat integration-tests/target/failsafe-reports/*IT.txt
      - run:
          when: on_fail
          command: cat integration-tests/target/failsafe-reports/*dump*

  snyk-scan:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: ./mvnw clean install -Pci -Dlicense.skip=true -Dmaven.test.skip.exec=true
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: false
          skip-unresolved: false
          run-on-non-main: true
          additional-arguments: "--maven-aggregate-project"

  reversing-labs:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            sudo pip install --upgrade pip
      - run:
          name: Download Reverse Labs Scanner
          command: |
            curl https://dso-resources.oktasecurity.com/scanner \
              -H "x-api-key: $DSO_RLSECURE_TOKEN" \
              --output rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      - run:
          name: Install RL Wrapper
          command: |
            pip install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      - aws-cli/setup:
          profile_name: default
          role_arn: $AWS_ARN
          region: us-east-1
      - run: >-
          eval "$(aws configure export-credentials --profile default --format env)" 2> /dev/null
      - run:
          name: Run Reversing Labs Wrapper Scanner
          command: |
            rl-wrapper \
              --artifact ${CIRCLE_WORKING_DIRECTORY/#\~/$HOME} \
              --name $CIRCLE_PROJECT_REPONAME\
              --version $CIRCLE_SHA1\
              --repository $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --commit $CIRCLE_SHA1 \
              --build-env "circleci" \
              --suppress_output

workflows:
  "Circle CI Tests":
    jobs:
      - build-and-test:
          name: jdk17
          node_image: cimg/openjdk:17.0.11-node
      - build-and-test:
          name: jdk21
          node_image: cimg/openjdk:21.0.2-node
      - snyk-scan:
          name: execute-snyk
          context:
            - static-analysis
  "Malware Scanner":
    jobs:
      - reversing-labs:
          context:
            - static-analysis