version: 2.1

orbs:
  platform-orb: okta/general-platform-helpers@1.2.3

aliases:

  - &build_steps
    - checkout
    - platform-orb/load-dependencies
    - run: java -version
    - run: ./mvnw clean install -Dlicense.skip=true -Pci
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*IT.txt
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*dump*

jobs:

  cache-secrets:
    machine: true
    resource_class: okta/generic-linux-x86
    environment:
      VAULT_ADDR: https://vault.aue1e.saasure.net
    steps:
      - checkout
      - run:
          name: "Vault login"
          command: |
            vault login -method=userpass username=$vault_username password=$vault_password > /dev/null 2>&1
      - platform-orb/save-dependencies

  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
  
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
          
  jdk17:
    docker:
      - image: circleci/openjdk:17
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

workflows:
  "Circle CI Tests":
    jobs:
      - cache-secrets
      - jdk8:
          requires:
            - cache-secrets
      - jdk11:
          requires:
            - cache-secrets
      - jdk17:
          requires:
            - cache-secrets
